
# **Lab 1: Recommendation System and Matrix Factorization**
 

####  Write code to fit a UV decomposition for the Netflix competition 

In [36]:
import numpy as np

In [37]:
# Use the following matrix as an example. Here 0's means "empty"
Y = np.array([[5, 1, 4, 5, 1], [0, 5, 2, 1, 4], [1, 4, 1, 1, 2],\
              [4, 1, 5, 5, 4], [5, 3, 3, 5, 4], [1, 5, 1, 0, 1], \
              [5, 1, 5, 5, 4]])
print(Y)

[[5 1 4 5 1]
 [0 5 2 1 4]
 [1 4 1 1 2]
 [4 1 5 5 4]
 [5 3 3 5 4]
 [1 5 1 0 1]
 [5 1 5 5 4]]


In [38]:
n = 7
m = 5
k = 2
U = np.reshape(np.random.uniform(0, 1, size= n*k), (n, k))
print(U)
V = np.reshape(np.random.uniform(0, 1, size= m*k), (m, k))
print(V)

[[ 0.18203286  0.32094623]
 [ 0.86717535  0.19716813]
 [ 0.75787096  0.65821282]
 [ 0.32810797  0.76469917]
 [ 0.64212889  0.67015957]
 [ 0.4888564   0.35910549]
 [ 0.11749311  0.50660816]]
[[ 0.56293223  0.76718513]
 [ 0.01539567  0.48334356]
 [ 0.56352884  0.20793107]
 [ 0.46278888  0.66128435]
 [ 0.43809051  0.30590566]]


In [39]:
N = np.sum(Y > 0)
print(N)
R = np.ones((n, m))
print R
R[Y == 0] = 0
print R

33
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [41]:
for i in range(5000):
    aa = 0.01/N
    AA = aa*(Y - np.dot(U, V.T))*R
    U = U + np.dot(AA, V)
    V = V + np.dot(AA.T, U)
    Err = np.sum((Y - np.dot(U, V.T)*R)**2)/N
    if i % 100 == 0:
        print(Err)


1.85374720213
1.78675757857
1.71355821807
1.61946700434
1.4974219186
1.34529430474
1.16799165613
0.97894893469
0.797724223156
0.643074539593
0.525561587675
0.445131154782
0.394497919933
0.364383961343
0.346968780491
0.336903771377
0.330955271083
0.32730207966
0.324952530417
0.32336967342
0.322258087193
0.321449997107
0.320846089811
0.320384860228
0.320026508643
0.319744246327
0.319519426981
0.319338705812
0.319192310925
0.319072949384
0.318975090426
0.318894481673
0.318827814365
0.318772486812
0.31872643425
0.318688004527
0.318655866006
0.31862893848
0.318606340728
0.318587350285
0.318571372255
0.31855791493
0.318546570536
0.318536999937
0.31852892037
0.318522095566
0.31851632773
0.318511451002
0.318507326109
0.318503835953


In [31]:
print np.dot(U, V.T)
print Y

[[ 4.30191576  0.35240525  3.95525978  4.73911285  2.71204783]
 [ 2.35115611  5.35202242  1.94584388  1.44494651  3.25602731]
 [ 1.3139206   3.8740079   1.05047077  0.61149051  2.1232001 ]
 [ 4.82117501  1.23305644  4.39761246  5.12512077  3.32754454]
 [ 4.61795722  3.00253114  4.13604528  4.50481332  3.81349365]
 [ 0.78968777  4.61480196  0.53569271 -0.13997315  2.06215592]
 [ 5.10994408  1.25290487  4.66327127  5.44408198  3.50828378]]
[[5 1 4 5 1]
 [0 5 2 1 4]
 [1 4 1 1 2]
 [4 1 5 5 4]
 [5 3 3 5 4]
 [1 5 1 0 1]
 [5 1 5 5 4]]


In [32]:
U

array([[ 0.4534478 ,  1.88564936],
       [ 2.04935678,  0.07832051],
       [ 1.45361168, -0.11921889],
       [ 0.80082787,  1.9585672 ],
       [ 1.40307328,  1.53983273],
       [ 1.67201473, -0.49365664],
       [ 0.82993656,  2.08584537]])

In [33]:
V

array([[ 1.06990962,  2.02411312],
       [ 2.62857684, -0.44521381],
       [ 0.8773908 ,  1.88656965],
       [ 0.61467287,  2.3654402 ],
       [ 1.5480655 ,  1.06598872]])